{
 "title": "teste monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Health Check ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memory_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "avg by(instance) (changes(predict_queries_total{job=\"ml_monitoring\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "avg by(__name__) (rate(predict_response_time_milliseconds_bucket{job=\"ml_monitoring\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Concept Drift",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 5 },
   "targets": [
    { "expr": "concept_drift", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Data Drift",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 5 },
   "targets": [
    { "expr": "data_drift", "legendFormat": "__auto" }
   ]
  }
 ]
}